### ISSUE TITLE
A little problem with  the output

### ISSUE THREAD

**Issue by NaiCity** [trimstray/htrace.sh#1]
Hey there,

As part of the output , I'm getting this before the rest of the output

curl: unknown --write-out variable: 'http_version'
curl: unknown --write-out variable: 'scheme'

What does this imply ? Please check out the attached photo
![htrace](https://user-images.githubusercontent.com/33538075/42745858-9ab8be7a-88dd-11e8-9524-9f6f5835addd.PNG)

**Comment by trimstray** [comment]
Hi!

Which **curl** version do you use?

Please read this: [curl-manpage](https://curl.haxx.se/docs/manpage.html). Probably updating the **curl** to the newest version will solve the problem.

**Comment by NaiCity** [comment]
I'm running curl 7.47.0

**Comment by trimstray** [comment]
**http_version**
The http version that was effectively used. (Added in 7.50.0)

**scheme**
The URL scheme (sometimes called protocol) that was effectively used (Added in 7.52.0)

**Comment by trimstray** [comment]
Updated: 17f289cfefb7b5994a19044722a10f8eb3326ddf
