### ISSUE TITLE
tput: No value for $TERM and no -T specified in Docker htrace

### ISSUE THREAD

**Issue by guidtz** [trimstray/htrace.sh#19]
Hello,

   I build a container with the Docker file but when I try to run it 
docker run --rm htrace --domain https://domaine.com

I have the error : 
tput: No value for $TERM and no -T specified

Where is my mistake ?

Regards

**Comment by trimstray** [comment]
Hi! Please check this:

```
# Description:
#
#   This Dockerfile builds a static htrace.sh in a Docker container.
#
#   For build:
#     docker build --rm -t htrace.sh -f Dockerfile .
#
#   For init:
#     docker run --rm -it --name htrace.sh htrace.sh -d http://nmap.org -h
#
#   For debug:
#     docker exec -it htrace.sh /bin/bash
#     docker run --rm -it --entrypoint /bin/bash --name htrace.sh htrace.sh
```

**Comment by guidtz** [comment]
Ok it seems to work.

Thanks

**Comment by andig** [comment]
Same problem here. I've just used the build script provided in the repository- shouldn't this work as expected?
