### ISSUE TITLE
Can I do traceroute like functionality without admin privileges?

### ISSUE THREAD

**Issue by JohnReedLOL** [trimstray/htrace.sh#30]
I need to do something like traceroute/tracepath/tracert, but I have no admin privileges and I do not have traceroute/tracepath/tracert installed. All I have is Java, Python, cygwin, and Windows 7, and I can put things in my home directory but I cannot do full installations. Do you have or know of a way to do traceroute/tracepath/tracert given these limitations?

**Comment by JohnReedLOL** [comment]
Full Question: https://serverfault.com/questions/944292/how-do-i-do-traceroute-tracepath-without-any-admin-privileges

**Comment by trimstray** [comment]
Your question is not related to this tool. Ask them in the forum or search for help on google.
