### ISSUE TITLE
Package for distros

### ISSUE THREAD

**Issue by rugk** [trimstray/htrace.sh#32]
It would be good to package this for distros. So I can just do "apt/dnf/… install" and I have it.

Maybe we can use this issue to try to make this happen?

**Comment by trimstray** [comment]
Hmm ... a good suggestion! For now I have no idea how to do it but if you can help - it will be great!

**Comment by trimstray** [comment]
At this moment, it is too time-consuming.

**Comment by rugk** [comment]
Nobody said, you should do so. This is certainly an issue for contributors…

So I'D label it as "help wanted" and see whether someone wants to bring it to their favorite distro or so…
