### ISSUE TITLE
macOS: readlink: illegal option -- f

### ISSUE THREAD

**Issue by Niek** [trimstray/htrace.sh#46]
Both setup.sh and htrace.sh show the error:
```bash
readlink: illegal option -- f
```
The easiest solution is probably to ask macOS users to do ``brew install coreutils`` and replace all ``readlink`` calls with ``greadlink`` if it exists.

**Comment by Niek** [comment]
A list of all packages required to get it up&running on macOS (might be good to add to the README):
```bash
brew install coreutils testssl ssllabs-scan jq nmap openssl
npm install -g observatory-cli
composer global require bramus/mixed-content-scan
```

**Comment by Niek** [comment]
PR created: https://github.com/trimstray/htrace.sh/pull/48

**Comment by berlincount** [comment]
`brew install composer` is missing ...

**Comment by Niek** [comment]
It's added in the new https://github.com/trimstray/htrace.sh/blob/master/dependencies.sh file - I'm closing the issue.
