### ISSUE TITLE
Cannot build a Docker image by `Unsupported system version.`

### ISSUE THREAD

**Issue by beatak** [trimstray/htrace.sh#54]
As [How to use](https://github.com/trimstray/htrace.sh#how-to-use) says, I ran `cd htrace.sh/build && docker build --rm -t htrace.sh -f Dockerfile .` and I got a failure with `Unsupported system version.`.

It seems the failure happens on [the line 96 of Dockerfile](https://github.com/trimstray/htrace.sh/blob/master/build/Dockerfile#L96), which executes [setup.sh](https://github.com/trimstray/htrace.sh/blob/master/setup.sh#L6-L21)

```
if [[ "$OSTYPE" == "darwin"* ]] ; then
  [ ! -z "$(brew --prefix)" ] && PATH=$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH
  readonly _dir=$(dirname "$(readlink "$0" || echo "$(echo "$0" | sed -e 's,\\,/,g')")")
elif [[ "$OSTYPE" == "linux-gnu" ]] ; then
  readonly _dir=$(dirname "$(readlink -f "$0" || echo "$(echo "$0" | sed -e 's,\\,/,g')")")
else
  printf "Unsupported system version.\\n"
  exit 1
fi
```

With the Dockerfile, this shell script is executed in `alpine:latest` image, and `$OSTYPE` returns `linux-musl`.

**Comment by tomtheun** [comment]
Had the same issue when building the Docker image. After fixing it locally it breaks on the same check in \'[bin/htrace.sh](https://github.com/trimstray/htrace.sh/blob/master/bin/htrace.sh#L52)\'.
