### ISSUE TITLE
Script error on MacOS/Darwin

### ISSUE THREAD

**Issue by qifuren1985** [trimstray/htrace.sh#58]
error output:
./bin/../lib/DomainCertCheck: line 133: unexpected EOF while looking for matching `)'
./bin/../lib/DomainCertCheck: line 335: syntax error: unexpected end of file

how to fix:
remove line 136

![image](https://user-images.githubusercontent.com/187371/53886676-82aba780-405b-11e9-9ad3-f0694168657d.png)

**Comment by trimstray** [comment]
What version of `bash` do you use?

**Comment by qifuren1985** [comment]
> What version of `bash` do you use?

bash 3.2

![image](https://user-images.githubusercontent.com/187371/53928376-d1d9f280-40c4-11e9-8f9e-9705a847a6bd.png)

**Comment by trimstray** [comment]
Please see [Requirements](https://github.com/trimstray/htrace.sh/wiki/Requirements).
