### ISSUE TITLE
Not working "--observatory" on MacOS/Darwin with Docker

### ISSUE THREAD

**Issue by urajio** [trimstray/htrace.sh#61]
$ docker run --rm -it --name htrace.sh htrace.sh -u https://nmap.org --observatory

     htrace.sh v1.1.2  (openssl 1.1.1a: ok)

    URI: https://nmap.org

         - request-method: GET

    req  time_total   time_connect    local_socket           via              remote_socket         geo   proto   ver   code     next_hop
    ---  ----------   ------------    ------------           ---              -------------         ---   -----   ---   ----     --------
 •   1   1.664089     1.664089        172.17.0.2:55862       213.87.104.168   45.33.49.119:443            https   1.1   200

    Mozilla Observatory (https://observatory.mozilla.org)

     ▸ https://nmap.org

         › env: ‘node’: No such file or directory
         › env: ‘node’: No such file or directory
         › env: ‘node’: No such file or directory
         › env: ‘node’: No such file or directory
         › env: ‘node’: No such file or directory

**Comment by trimstray** [comment]
Fixed: [#65](https://github.com/trimstray/htrace.sh/issues/65)
