### ISSUE TITLE
Color Output

### ISSUE THREAD

**Issue by adblockanti** [trimstray/htrace.sh#64]
Sometimes it ist very useful to redirect the output to a file
like sudo htrace.sh -u https://nmap.org -s -h | tee htrace.txt

The problem with this is the colored output.
(It produces nonprintable chars)
....
URI: ^[[4;1;33mhttps://^[[4;1;33mwww.badssl.com/^[[m

         - request-method: ^[[2;1;30mGET^[[m

Please make an option to disable color output like for grep --color=never

Thanks.

**Comment by trimstray** [comment]
```bash
export HTRACE_COLORS=off ; htrace.sh -u htrace.sh -u https://nmap.org -s -h
```
